#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$path = $argv[1] ?? 'app';

$latte = new Latte\Engine;
$latte->addExtension(new Nette\Bridges\ApplicationLatte\UIExtension(null));
$latte->addExtension(new Nette\Bridges\AssetsLatte\LatteExtension(new Nette\Assets\Registry));
$latte->addExtension(new App\Presentation\Accessory\LatteExtension);
$latte->addExtension(new Latte\Tools\LinterExtension);

$linter = new Latte\Tools\Linter($latte, strict: true);
$ok = $linter->scanDirectory($path);
exit($ok ? 0 : 1);
